add rewards and get_reward capabilities to CollectGems
JuliaReinforcementLearning/GridWorlds.jl pull request #45
Opened 2020-10-12 12:32 UTC by Sid-Bhatia-0

Added rewards into the `CollectGems` env struct. The field `r` will maintain the step reward received from the immediately previous action.

Overloaded the default method for `TURN_LEFT` and `TURN_RIGHT` actions in order to update the `env.r` field on every action taken.

Not re-implementing a time penalty for each step taken. Can incorporate this feature using [RewardOverriddenEnv](https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/blob/d2d82b4b0a71d48d5a0820cd2eda3b8db08abf17/src/implementations/environments.jl#L127)

2020-10-12 14:08 UTC, findmyway requested changes
I feel that the `default_reward` field is a little over-designed here. I understand that you want to grant a reward(or penalty?) for each step. This seems like a common requirement, how about creating a general wrapper later?

2020-10-12 14:08 UTC, findmyway commented on src/envs/collectgems.jl
> +end
A one-line function would be better here.

2020-10-12 15:13 UTC, Sid-Bhatia-0 commented on src/envs/collectgems.jl
> +end
Sure. Will make it a one-line definition.

2020-10-12 18:26 UTC, Sid-Bhatia-0 commented on src/envs/collectgems.jl
>      if !w.world[WALL, dest]
There will always need to be a default value of step reward.

It will be `0` by default, that is, each step `env(action)`, if it doesn't do anything special (like moving to a gem-filled cell) will need to update the step reward to 0 (using `w.r = 0` for example, where the `0` is hard-coded). If this update doesn't occur, then the previous reward will linger around, which is not good. For example, if the agent turns left after moving into a gem-cell and if we don't update this to 0 from 1 (the previous reward on receiving a gem), then the agent receives double-reward for the same gem. I am just mentioning this for a more complete context.

I just parameterized that hard-code value to a field of the environment struct.

Of course, as you rightly pointed out, the per step penalty can also be done using a general wrapper (like [RewardOverriddenEnv](https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/blob/d2d82b4b0a71d48d5a0820cd2eda3b8db08abf17/src/implementations/environments.jl#L127)) later. Even if we wrap it later, we will still be hardcoding that '0' right now.

Since the per step penalty is somewhat crucial for this environment (and arguably for other goal-seeking environments as well), how about we remove the `default_reward` field from the struct and at least parameterize that `0` (or a small negative number) as a global const variable for that environment?

2020-10-13 01:39 UTC, findmyway commented on src/envs/collectgems.jl
>      if !w.world[WALL, dest]
> I just parameterized that hard-code value to a field of the environment struct.

Yeah, that's my point. I think a hardcoded value of 0 would be enough here. Adding an extra field brings in unnecssary confusion. Generally you don't want to add a such field to every env in this package. If so, we may consider writing a general wrapper.

2020-10-13 06:37 UTC, Sid-Bhatia-0 commented on src/envs/collectgems.jl
>      if !w.world[WALL, dest]
Hmm.. I think I get it now. I'll summarize my understanding. Correct me if I am missing something..

1. We should not add such a field to every env. Totally makes sense.
2. And instead of using a struct field if we use a global const (to parameterize that `0`), that provides a little too much room for flexibility (and consequently complexity) which is also not good.
3. And we can add a standard wrapper that will make it loud and clear that it is "per step penalty" type environment, instead of scrambling through the source code to figure this out for each environment.
4. And this standard wrapper should be used anywhere this "per step penalty" feature is required. So this would also keep things consistent.

I'll make the necessary changes.

2020-10-13 08:09 UTC, merged